// We create the Authors 
// Then we make use of the authorsId to create the book
### GetAll
http://localhost:3000/authors 

### Get author by Id
http://localhost:3000/authors/691b436b6835068ce0a0b360

### Create author
POST http://localhost:3000/authors
content-type: application/json

{
  "name": "Deborah Sarah",
  "birthYear": 1977,
  "nationality": "Nigerian"
}

### Put Book by Id
PUT http://localhost:3000/authors/6919c7c6a4981960c5cc1e1b HTTP/1.1 
content-type: application/json

{
  "name": "Chimamanda Adichie",
  "birthYear": 1977,
  "nationality": "American"
}

### Delete Author by id
DELETE http://localhost:3000/authors/691c1970dc692d6ba1f1c708 HTTP/1.1 


//Books

### GetAll
http://localhost:3000/books 

### Get book by id
http://localhost:3000/books/691b6b0c276d15828a3118d5

### Create book
POST http://localhost:3000/books
content-type: application/json

{
  "title": "Purple Lavender",
  "genre": "FicRomancetion",
  "isbn": "9780143104916",
  "publishedYear": 2000,
  "pages": 300,
  "available": false,
  "authorId": "691df13c699f003bb51d44e6"
}

### Put book
PUT http://localhost:3000/books/691b3d57126f145c7239efce HTTP/1.1 
content-type: application/json

{
  "title": "The Power of Self-Discipline",
  "genre": "Self-Help",
  "isbn": "9780735211442",
  "publishedYear": 2002,
  "pages": 350,
  "available": false,
  "authorId": "691b436b6835068ce0a0b360"
}


### Delete book
DELETE http://localhost:3000/books/691b6b0c276d15828a3118d5 HTTP/1.1 
content-type: application/json



